name: Build and deploy
on:
  push:
    branches:
      - master
      - feature/**
    tags:
      - v*.*.*

jobs:
  build:
    uses: infra/workflows/.gitea/workflows/docker.yaml@956337b9bd5e72a93d3a57513cd421e7554dd61d
    secrets: inherit
    with:
      webhook_url: ${{ secrets.WEBHOOK_URL }}
